name: Bonfhir PR

on:
  pull_request:
  
jobs:
  build_pr:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required to support lerna --since command

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: Install packages
        run: yarn install --immutable

      - name: Check
        run: yarn lerna run check --since=origin/main

      - name: Build
        run: yarn lerna run build --since=origin/main

      - name: Test
        run: yarn lerna run test --since=origin/main -- --coverage

      - name: Upload code coverage
        uses: codecov/codecov-action@v3
